### ISSUE TITLE
New Alpine version seems to have broken the actions

### ISSUE THREAD

**Issue by Yaronn44** [ScottBrenner/generate-changelog-action#32]
When I use the action in my CI I have the following error since today : 
```
 Step 3/7 : RUN apk --no-cache add git nodejs-npm
   ---> Running in 0bc4189572d0
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    nodejs-npm (no such package):
      required by: world[nodejs-npm]
  The command '/bin/sh -c apk --no-cache add git nodejs-npm' returned a non-zero code: 1
```

There is a new version of Alpine since yesterday and the error seems to come from here.

**Comment by PeterDaveHello** [comment]
nodejs/docker-node#1496 is just an issue for Alpine v3.14 to be added to the official node.js Docker image, doesn't have anything to do with the package repository of Alpine Linux.

Not sure if this is something you need:
https://pkgs.alpinelinux.org/package/v3.14/main/x86_64/npm

`nodejs-npm` was quite an old package name of it until Alpine Linux v3.7
https://pkgs.alpinelinux.org/packages?name=*npm*&branch=v3.8&arch=x86_64

It's just `npm` since Alpine Linux v3.8
https://pkgs.alpinelinux.org/packages?name=*npm*&branch=v3.8&arch=x86_64

**Comment by Yaronn44** [comment]
Ok got it about the node.js Docker issue. Just updated my last comment.

So if I understand well in the Dockerfile the :
`RUN apk --no-cache add git nodejs-npm`
should be replace by :
`RUN apk --no-cache add git nodejs`

Actually I'm just using this Action and all of my CI is broken now, so I'm just trying to figure out what goes wrong...

**Comment by ScottBrenner** [comment]
Thanks for reporting this! Fix released in
- https://github.com/ScottBrenner/generate-changelog-action/releases/tag/v1.3.1
- https://github.com/ScottBrenner/generate-changelog-action/pkgs/container/generate-changelog-action
